name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        # Handle Rollup optional dependencies issue on Linux
        echo "Installing dependencies with Rollup fix..."
        npm cache clean --force
        rm -rf node_modules package-lock.json
        npm install
        # Regenerate lock file for consistency
        npm install --package-lock-only

    - name: Run linter
      run: npm run lint

    - name: Run tests with coverage
      run: npm run test:coverage

    - name: Test Results Summary
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ All tests passed!"
        else
          echo "❌ Some steps failed. Check the logs above."
        fi

    - name: Build application
      run: npm run build
      if: success() || failure() # Run even if tests fail

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      if: always() # Always upload coverage if it exists
      with:
        name: coverage-reports-node${{ matrix.node-version }}
        path: coverage/
        retention-days: 7
        if-no-files-found: warn

    - name: Comment coverage on PR
      uses: codecov/codecov-action@v4
      if: github.event_name == 'pull_request'
      with:
        files: ./coverage/coverage-final.json
        fail_ci_if_error: false 